# Generated by Django 5.1.4 on 2025-02-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('MECH', 'Mechanical')], max_length=4)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
